# Target rules
all: build
	@echo "Building pcluster_2az_sacct"

build: assets

assets:
	@echo "Build assets for pcluster_2az_sacct"

run: build
	@echo "Run assets for pcluster_2az_sacct"

test: build

clean:

clobber: clean