AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to bootstrap RES VDI Windows

Resources:
  RESVDIWindowsInstaller:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'research-and-engineering-studio-vdi-windows'
      Description: RES VDI Bootstrap for Windows
      Version: '0.0.1'
      Platform: Windows
      Data: !Sub |
        #  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
        #
        #  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
        #  with the License. A copy of the License is located at
        #
        #      http://www.apache.org/licenses/LICENSE-2.0
        #
        #  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
        #  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
        #  and limitations under the License.
        name: research-and-engineering-studio-vdi-windows
        description: An RES EC2 Image Builder component to install required RES software dependencies for Windows VDI.
        schemaVersion: 1.0
        parameters:
          - AWSAccountID:
              type: string
              description: RES Environment AWS Account ID
          - RESEnvName:
              type: string
              description: RES Environment Name
          - RESEnvRegion:
              type: string
              description: RES Environment Region
          - RESEnvReleaseVersion:
              type: string
              description: RES Release Version

        phases:
          - name: build
            steps:
              - name: CreateRESBootstrapFolder
                action: CreateFolder
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    - path: 'C:\Users\Administrator\RES\Bootstrap'
                      overwrite: true
              - name: DownloadRESWindowsInstallPackage
                action: S3Download
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    - source: 's3://{{ RESEnvName }}-cluster-{{ RESEnvRegion }}-{{ AWSAccountID }}/idea/vdc/res-ready-install-script-packages/windows/res_windows_install_{{ RESEnvReleaseVersion }}.tar.gz'
                      destination: '{{ build.CreateRESBootstrapFolder.inputs[0].path }}\res_windows_install_{{ RESEnvReleaseVersion }}.tar.gz'
                      expectedBucketOwner: '{{ AWSAccountID }}'
              - name: RunInstallScript
                action: ExecutePowerShell
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    commands:
                        - 'cd {{ build.CreateRESBootstrapFolder.inputs[0].path }}'
                        - 'Tar -xf res_windows_install_{{ RESEnvReleaseVersion }}.tar.gz'
                        - 'Import-Module .\virtual-desktop-host-windows\Install.ps1'
                        - 'Install-WindowsEC2Instance'
              - name: Reboot
                action: Reboot
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    delaySeconds: 0  


Outputs:
  ImageBuilderComponent:
    Value: !Ref RESVDIWindowsInstaller
