AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to bootstrap RES VDI Linux

Resources:
  RESVDILinuxInstaller:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'research-and-engineering-studio-vdi-linux'
      Description: RES VDI Bootstrap for Linux
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        #  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
        #
        #  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
        #  with the License. A copy of the License is located at
        #
        #      http://www.apache.org/licenses/LICENSE-2.0
        #
        #  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
        #  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
        #  and limitations under the License.
        name: research-and-engineering-studio-vdi-linux
        description: An RES EC2 Image Builder component to install required RES software dependencies for Linux VDI.
        schemaVersion: 1.0
        parameters:
          - AWSAccountID:
              type: string
              description: RES Environment AWS Account ID
          - RESEnvName:
              type: string
              description: RES Environment Name
          - RESEnvRegion:
              type: string
              description: RES Environment Region
          - RESEnvReleaseVersion:
              type: string
              description: RES Release Version

        phases:
          - name: build
            steps:
              - name: PrepareRESBootstrap
                action: ExecuteBash
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    commands:
                        - 'mkdir -p /root/bootstrap/logs'
                        - 'mkdir -p /root/bootstrap/latest'
              - name: DownloadRESLinuxInstallPackage
                action: S3Download
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    - source: 's3://{{ RESEnvName }}-cluster-{{ RESEnvRegion }}-{{ AWSAccountID }}/idea/vdc/res-ready-install-script-packages/linux/res_linux_install_{{ RESEnvReleaseVersion }}.tar.gz'
                      destination: '/root/bootstrap/res_linux_install_{{ RESEnvReleaseVersion }}.tar.gz'
                      expectedBucketOwner: '{{ AWSAccountID }}'
              - name: RunInstallScript
                action: ExecuteBash
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    commands:
                        - 'tar -xvf {{ build.DownloadRESLinuxInstallPackage.inputs[0].destination }} -C /root/bootstrap/latest'
                        - '/bin/bash /root/bootstrap/latest/virtual-desktop-host-linux/install.sh -r {{ RESEnvRegion }} -n {{ RESEnvName }} -g NONE'
              - name: FirstReboot
                action: Reboot
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    delaySeconds: 0
              - name: RunInstallPostRebootScript
                action: ExecuteBash
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    commands:
                        - '/bin/bash /root/bootstrap/latest/virtual-desktop-host-linux/install_post_reboot.sh'
              - name: SecondReboot
                action: Reboot
                onFailure: Abort
                maxAttempts: 3
                inputs:
                    delaySeconds: 0      


Outputs:
  ImageBuilderComponent:
    Value: !Ref RESVDILinuxInstaller
