# Target rules
all: build
	@echo "Building login_node_for_res"

build: assets

assets:
	@echo "Build assets for login_node_for_res"

run: build
	@echo "Run assets for login_node_for_res"

test: build

clean:

clobber: clean