# Target rules
all: build
	@echo "Building hpc_ready_ami"

build: assets

assets:
	@echo "Build assets for hpc_ready_ami"

run: build
	@echo "Run assets for hpc_ready_ami"

test: build

clean:

clobber: clean