# Target rules
all: build
	@echo "Building serverless_openldap"

build: assets

assets:
	@echo "Build assets for serverless_openldap"

run: build
	@echo "Run assets for serverless_openldap"

test: build

clean:

clobber: clean