# Target rules
all: build
	@echo "Building benchmark_hpc6id"

build: assets

assets:
	@echo "Build assets for benchmark_hpc6id"

run: build
	@echo "Run assets for benchmark_hpc6id"

test: build

clean:

clobber: clean