# Target rules
all: build
	@echo "Building benchmark_hpc7a"

build: assets

assets:
	@echo "Build assets for benchmark_hpc7a"

run: build
	@echo "Run assets for benchmark_hpc7a"

test: build

clean:

clobber: clean