# Target rules
all: build
	@echo "Building res_ready_ami"

build: assets

assets:
	@echo "Build assets for res_ready_ami"

run: build
	@echo "Run assets for res_ready_ami"

test: build

clean:

clobber: clean