AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EFS filesystem, mount targets, and a client security group for access to the filesystem

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Filesystem Options
        Parameters:
          - AutomaticBackups
          - ThroughputMode
      - Label:
          default: Networking and Access
        Parameters:
          - VpcId
          - SubnetIds
          - SubnetCount

Parameters:
  VpcId:
    Description: VPC where you will deploy the EFS filesystem
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Description: Choose up to three subnets in different AZs in the VPC
    Type: List<AWS::EC2::Subnet::Id>
  AutomaticBackups:
    Description: Automatic backups for the filesystem
    Type: String
    Default: DISABLED
    AllowedValues:
         - "ENABLED"
         - "DISABLED"
  SubnetCount:
    Description: Count of subnets selected in SubnetIds (must match)
    Type: String
    Default: "3"
    AllowedValues:
         - "1"
         - "2"
         - "3"
  ThroughputMode:
    Description: EFS filesystem throughput mode
    Type: String
    Default: "elastic"
    AllowedValues:
         - "elastic"
         - "bursting"

Conditions:
  1AZCondition: !Or
    - !Equals [!Ref 'SubnetCount', '1']
    - !Condition '2AZCondition'
  2AZCondition: !Or
    - !Equals [!Ref 'SubnetCount', '2']
    - !Condition '3AZCondition'
  3AZCondition: !Equals [!Ref 'SubnetCount', '3']

Resources:

  EfsFilesystem:
    Type: AWS::EFS::FileSystem
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-efs"
      FileSystemPolicy:
        Version: 2012-10-17
        Id: efs-prevent-anonymous-access-policy
        Statement:
          - Sid: efs-statement
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'elasticfilesystem:ClientRootAccess'
              - 'elasticfilesystem:ClientWrite'
              - 'elasticfilesystem:ClientMount'
            Condition:
              Bool:
                'elasticfilesystem:AccessedViaMountTarget': 'true'
      BackupPolicy: 
        Status: !Ref AutomaticBackups
      Encrypted: true
      ThroughputMode: !Ref ThroughputMode

  # Security group
  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub 
       - 'Allows traffic to EFS filesystem ${FileSystemId}'
       - FileSystemId: !Ref EfsFilesystem
      GroupName: !Sub '${AWS::StackName}-efs-security-group'
      VpcId: !Ref VpcId

  # Clients join this group for access to the EFS file system
  EfsClientSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub
        - 'Clients join this group for access to EFS filesystem ${FileSystemId}'
        - FileSystemId: !Ref EfsFilesystem
      GroupName: !Sub '${AWS::StackName}-efs-client-security-group'
      VpcId: !Ref VpcId

  EfsSecurityGroupInboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      Description: Allow incoming traffic to EFS from members of security group
      FromPort: 2049
      ToPort: 2049
      GroupId: !Ref EfsSecurityGroup
      SourceSecurityGroupId: !Ref EfsClientSecurityGroup

  EfsClientSecurityGroupOutboundRule:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      IpProtocol: tcp
      Description: Allow outgoing traffic from members of security group to EFS
      FromPort: 2049
      ToPort: 2049
      GroupId: !Ref EfsClientSecurityGroup
      DestinationSecurityGroupId: !Ref EfsSecurityGroup

  EfsMountTarget1:
    Type: AWS::EFS::MountTarget
    Condition: 1AZCondition
    Properties:
         FileSystemId: !Ref EfsFilesystem
         SecurityGroups:
              - !Ref EfsSecurityGroup
         SubnetId: !Select [ 0, !Ref SubnetIds ]

  EfsMountTarget2:
    Type: AWS::EFS::MountTarget
    Condition: 2AZCondition
    Properties:
         FileSystemId: !Ref EfsFilesystem
         SecurityGroups:
              - !Ref EfsSecurityGroup
         SubnetId: !Select [ 1, !Ref SubnetIds ]

  EfsMountTarget3:
    Type: AWS::EFS::MountTarget
    Condition: 3AZCondition
    Properties:
         FileSystemId: !Ref EfsFilesystem
         SecurityGroups:
              - !Ref EfsSecurityGroup
         SubnetId: !Select [ 2, !Ref SubnetIds ]

Outputs:
  EFSFilesystemId:
    Description: The ID of the EFS filesystem that has been created
    Value: !Ref EfsFilesystem
    Export:
      Name: !Sub ${AWS::StackName}-EFSFilesystemId
  SecurityGroupId:
    Description: Clients join this grouo for access to the filesystem
    Value: !Ref EfsClientSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-SecurityGroupId

