AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Components for AWS PCS-ready AMIs

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  PcsAgentInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'PcsAgentInstaller-${AWS::StackName}'
      Description: Download and install the AWS PCS agent
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'AWS PCS agent installer'
        schemaVersion: 1.0
        parameters:
          - PcsAgentInstallerVersion:
              type: string
              description: 'Version of the AWS PCS agent installer to use'
              default: 'latest'
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/install-pcs-agent.sh -o install-pcs-agent.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-pcs-agent.sh'
                    - './install-pcs-agent.sh --aws-region=${AWS::Region} --pcs-agent-installer-version={{ PcsAgentInstallerVersion }}'

  PcsSlurmInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'PcsSlurmInstaller-${AWS::StackName}'
      Description: Download and install Slurm for AWS PCS
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'AWS PCS Slurm installer'
        schemaVersion: 1.0
        parameters:
          - PcsSlurmVersion:
              type: string
              description: 'Major version of Slurm to install'
              default: '23.11'
          - PcsSlurmInstallerVersion:
              type: string
              description: 'Version of the AWS PCS Slurm installer to use'
              default: 'latest'
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/install-pcs-slurm.sh -o install-pcs-slurm.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-pcs-slurm.sh'
                    - './install-pcs-slurm.sh --aws-region=${AWS::Region} --pcs-slurm-version={{ PcsSlurmVersion }} --pcs-slurm-installer-version={{ PcsSlurmInstallerVersion }}'

  EfaInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'EfaInstaller-${AWS::StackName}'
      Description: Download and install EFA software
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Elastic Fabric Adapter installer'
        schemaVersion: 1.0
        parameters:
          - EfaVersion:
              type: string
              description: 'EFA version to install'
              default: 'latest'
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/install-efa.sh -o install-efa.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-efa.sh'
                    - './install-efa.sh --efa-installer-version={{ EfaVersion }}'

  SpackInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'SpackInstaller-${AWS::StackName}'
      Description: Install Spack and optimized configurations
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Spack installer'
        schemaVersion: 1.0
        parameters:
          - Prefix:
              type: string
              description: 'Spack installation prefix'
              default: '/opt'
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/common.sh -o common.sh'
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/install-spack.sh -o install-spack.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-spack.sh'
                    - './install-spack.sh --prefix={{ Prefix }}'

  UpdateOsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'UpdateOs-${AWS::StackName}'
      Description: Update the OS on PCS-compatible AMI base images
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Update OS for PCS AMI'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/common.sh -o common.sh'
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/update-os.sh -o update-os.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x update-os.sh'
                    - './update-os.sh'
