AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Components for AWS PCS-ready AMIs

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:

  CloudwatchAgentStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-cloudwatch-agent.yaml'
      TimeoutInMinutes: 10

  EfaInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-efa.yaml'
      TimeoutInMinutes: 10

  EfsUtilsInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-efs-utils.yaml'
      TimeoutInMinutes: 10

  LustreInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-lustre.yaml'
      TimeoutInMinutes: 10

  PcsAgentInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-pcs-agent.yaml'
      TimeoutInMinutes: 10

  PcsSlurmInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-pcs-slurm.yaml'
      TimeoutInMinutes: 10

  SpackInstallerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-spack.yaml'
      TimeoutInMinutes: 10

  SsmAgentStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/install-ssm-agent.yaml'
      TimeoutInMinutes: 10

  OptimizePerformanceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/optimize-performance.yaml'
      TimeoutInMinutes: 10

  UpdateOsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        HpcRecipesS3Bucket: !Ref HpcRecipesS3Bucket
        HpcRecipesBranch: !Ref HpcRecipesBranch
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/components/update-os.yaml'
      TimeoutInMinutes: 10

Outputs:
  CloudwatchAgentComponent:
    Description: CloudwatchAgentComponent
    Value: !GetAtt [ CloudwatchAgentStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-CloudwatchAgentComponent"
  EfaInstallerComponent:
    Description: EfaInstallerComponent
    Value: !GetAtt [ EfaInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-EfaInstallerComponent"
  EfsUtilsInstallerComponent:
    Description: EfsUtilsInstallerComponent
    Value: !GetAtt [ EfsUtilsInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-EfsUtilsInstallerComponent"
  LustreInstallerComponent:
    Description: LustreInstallerComponent
    Value: !GetAtt [ LustreInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-LustreInstallerComponent"
  PcsAgentInstallerComponent:
    Description: PcsAgentInstallerComponent
    Value: !GetAtt [ PcsAgentInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-PcsAgentInstallerComponent"
  PcsSlurmInstallerComponent:
    Description: PcsSlurmInstallerComponent
    Value: !GetAtt [ PcsSlurmInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-PcsSlurmInstallerComponent"
  SpackInstallerComponent:
    Description: SpackInstallerComponent
    Value: !GetAtt [ SpackInstallerStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-SpackInstallerComponent"
  SsmAgentComponent:
    Description: SsmAgentComponent
    Value: !GetAtt [ SsmAgentStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-SsmAgentComponent"
  OptimizePerformanceComponent:
    Description: OptimizePerformanceComponent
    Value: !GetAtt [ OptimizePerformanceStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-OptimizePerformanceComponent"  
  UpdateOsComponent:
    Description: UpdateOsComponent
    Value: !GetAtt [ UpdateOsStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-UpdateOsComponent"
