AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to install EFA software

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

# TODO - parameterize EfaVersion
Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  EfaInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: EfaInstaller
      Description: Download and install EFA software
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Elastic Fabric Adapter installer'
        schemaVersion: 1.0
        parameters:
          - EfaVersion:
              type: string
              description: 'EFA version to install'
              default: 'latest'
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-efa.sh -o install-efa.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-efa.sh'
                    - './install-efa.sh --efa-installer-version={{ EfaVersion }}'


Outputs:
  ImageBuilderComponent:
    Value: !Ref EfaInstallerComponent
    Export:
      Name: !Sub 'EfaInstallerComponent'
