AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to install EFA software

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

# TODO - parameterize EfaVersion
Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  EfaInstaller:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'EfaInstaller-${AWS::StackName}'
      Description: Download and install EFA software
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Elastic Fabric Adapter installer'
        schemaVersion: 1.0
        parameters:
          - EfaVersion:
              type: string
              description: 'EFA version to install'
              default: 'latest'
        phases:
          - name: build
            steps:
              - name: DownloadInstaller
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-efa.sh
                    destination: install-efa.sh
              - name: InstallEfa
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'chmod +x install-efa.sh'
                    - './install-efa.sh --efa-installer-version={{ EfaVersion }}'


Outputs:
  ImageBuilderComponent:
    Value: !Ref EfaInstaller

