AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to install AWS PCS agent

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Installer Parameters
        Parameters:
          - PcsAgentInstallerVersion
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  PcsAgentInstallerVersion:
    Type: String
    Default: latest
    Description: Version of the AWS PCS agent installer to use
    AllowedPattern: '^(latest|[0-9]+)$'
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  PcsAgentInstaller:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'PcsAgentInstaller-${AWS::StackName}'
      Description: Download and install the AWS PCS agent
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'AWS PCS agent installer'
        schemaVersion: 1.0
        parameters:
          - PcsAgentInstallerVersion:
              type: string
              description: 'Version of the AWS PCS agent installer to use'
              default: '${PcsAgentInstallerVersion}'
        phases:
          - name: build
            steps:
              - name: DownloadInstaller
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-pcs-agent.sh
                    destination: install-pcs-agent.sh
              - name: InstallPcsAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'chmod +x install-pcs-agent.sh'
                    - './install-pcs-agent.sh --aws-region=${AWS::Region} --pcs-agent-installer-version={{ PcsAgentInstallerVersion }}'

Outputs:
  ImageBuilderComponent:
    Value: !Ref PcsAgentInstaller
