AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to install SSM agent

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  SsmAgentComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: SsmAgentInstaller
      Description: Install SSM Agent on PCS-compatible AMI base images
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Install SSM Agent'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh -o common.sh'
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-ssm-agent.sh -o install-ssm-agent.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - 'chmod +x install-ssm-agent.sh'
                    - './install-ssm-agent.sh'
Outputs:
  ImageBuilderComponent:
    Value: !Ref SsmAgentComponent
    Export:
      Name: !Sub 'SsmAgentComponent'
