AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Component to run OS updates when building PCS-compatible AMIs

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:
  UpdateOs:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub 'UpdateOs-${AWS::StackName}'
      Description: Update the OS on PCS-compatible AMI base images
      Version: '0.0.1'
      Platform: Linux
      Data: !Sub |
        name: 'Update OS for PCS AMI'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadScript
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh -o common.sh'
                    - 'curl -fsSL https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/update-os.sh -o update-os.sh'
              - name: InstallAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - 'chmod +x update-os.sh'
                    - './update-os.sh'

Outputs:
  ImageBuilderComponent:
    Value: !Ref UpdateOs
