# Target rules
all: build
	@echo "Building s3_demo_bucket"

build: assets

assets:
	@echo "Build assets for s3_demo_bucket"

run: build
	@echo "Run assets for s3_demo_bucket"

test: build

clean:

clobber: clean