# Target rules
all: build
	@echo "Building spack_shared_fs"

build: assets

assets:
	@echo "Build assets for spack_shared_fs"

run: build
	@echo "Run assets for spack_shared_fs"

test: build

clean:

clobber: clean