{
 "title": "Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pcs_cluster",
    "label": "PCS Cluster ID",
    "query": {
     "query": "label_values(slurm_partition_cpus_total,pcs_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU (Total)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU (Alloc)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_alloc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU (Idle)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU (Other)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_cpus_other", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU (Total)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_gpus_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU (Alloc)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_gpus_alloc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU (Idle)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_gpus_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU (Other)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_gpus_other", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pcs_cluster_id) (slurm_nodes_alloc{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_alloc{pcs_cluster_id=\"$pcs_cluster\"}) * 0)",
     "legendFormat": "Allocated Nodes"
    },
    {
     "expr": " sum by (pcs_cluster_id) (slurm_nodes_mix{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_mix{pcs_cluster_id=\"$pcs_cluster\"}) * 0)",
     "legendFormat": "Mixed Nodes"
    },
    {
     "expr": "sum by (pcs_cluster_id) (slurm_nodes_idle{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_idle{pcs_cluster_id=\"$pcs_cluster\"}) * 0)",
     "legendFormat": "Idle Nodes"
    },
    {
     "expr": " (sum by (pcs_cluster_id) (slurm_nodes_total{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_total{pcs_cluster_id=\"$pcs_cluster\"}) * 0)) - (sum by (pcs_cluster_id) (slurm_nodes_idle{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_idle{pcs_cluster_id=\"$pcs_cluster\"}) * 0)) - ( sum by (pcs_cluster_id) (slurm_nodes_mix{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_mix{pcs_cluster_id=\"$pcs_cluster\"}) * 0)) - (sum by (pcs_cluster_id) (slurm_nodes_alloc{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_alloc{pcs_cluster_id=\"$pcs_cluster\"}) * 0))",
     "legendFormat": "Other Nodes"
    },
    {
     "expr": " sum by (pcs_cluster_id) (slurm_nodes_total{pcs_cluster_id=\"$pcs_cluster\"}) or (absent(slurm_nodes_total{pcs_cluster_id=\"$pcs_cluster\"}) * 0)",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "group by (partition) (slurm_partition_cpus_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}