{
 "title": "Jobs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_id",
    "query": {
     "query": "label_values(slurm_job_node_info{job=\"slurm_exporter\"},job_id)"
    }
   },
   {
    "name": "slurm_node",
    "query": {
     "query": "label_values(slurm_job_node_info{job=\"slurm_exporter\", job_id=\"$job_id\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Jobs Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Allocated to Job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(slurm_job_node_info{job_id=\"$job_id\"})",
     "legendFormat": "Node Count"
    }
   ]
  },
  {
   "title": "Allocated Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "group by (instance, instance_id, instance_type, slurm_node) (\n    (\n      node_uname_info{job=\"node_exporter\"}\n        * on(slurm_node) group_left(job_id, job_name)\n        label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    \n \n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic (Aggregate)",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"system\", job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"user\", job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"iowait\", job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\".*irq\", job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(\n  irate(node_cpu_seconds_total{mode=\"idle\", job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) / scalar(\n  count(\n    count(\n      node_cpu_seconds_total\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (cpu, slurm_node)\n  )\n)",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Saturation per Core",
   "type": "timeseries",
   "description": "Shows CPU saturation per core, calculated as the proportion of time spent waiting to run relative to total time demanded (running + waiting).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(node_schedstat_waiting_seconds_total{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\"))\n/\n(irate(node_schedstat_running_seconds_total{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\") + irate(node_schedstat_waiting_seconds_total{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\"))\n",
     "legendFormat": "{{slurm_node}}: CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory (Aggregate)",
   "type": "timeseries",
   "description": "Breakdown of physical memory and swap usage. Hardware-detected memory errors are also displayed",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes{job=\"node_exporter\"} - node_memory_Buffers_bytes{job=\"node_exporter\"} - node_memory_Cached_bytes{job=\"node_exporter\"} - node_memory_Slab_bytes{job=\"node_exporter\"} - node_memory_PageTables_bytes{job=\"node_exporter\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}\n  )\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "sum(\n  node_memory_PageTables_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "sum(\n  node_memory_SwapCached_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "sum(\n  node_memory_Slab_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "sum(\n  node_memory_Cached_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "sum(\n  node_memory_Buffers_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "sum(\n  node_memory_MemFree_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "sum(\n  (\n    node_memory_SwapTotal_bytes{job=\"node_exporter\"} - node_memory_SwapFree_bytes{job=\"node_exporter\"}\n  )\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "sum(\n  node_memory_HardwareCorrupted_bytes{job=\"node_exporter\"}\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Memory Page Faults (Aggregate)",
   "type": "timeseries",
   "description": "Rate of memory page faults, split into total, major (disk-backed), and derived minor (non-disk) faults. High major fault rates may indicate memory pressure or insufficient RAM",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgfault{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")",
     "legendFormat": "Pgfault - Page major and minor fault ops"
    },
    {
     "expr": "irate(node_vmstat_pgmajfault{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")",
     "legendFormat": "Pgmajfault - Major page fault ops"
    },
    {
     "expr": "irate(node_vmstat_pgfault{job=\"node_exporter\"}[$__rate_interval]) * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")",
     "legendFormat": "Pgminfault - Minor page fault ops"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic (Aggregate)",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(\n      node_filesystem_size_bytes{device!~\"rootfs\", job=\"node_exporter\"}\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (mountpoint)\n    - \n    sum(\n      node_filesystem_avail_bytes{device!~\"rootfs\", job=\"node_exporter\"}\n      * on(slurm_node) group_left(job_id, job_name)\n      label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    ) by (mountpoint)\n  ) \n  / \n  sum(\n    node_filesystem_size_bytes{device!~\"rootfs\", job=\"node_exporter\"}\n    * on(slurm_node) group_left(job_id, job_name)\n    label_replace(slurm_job_node_info{job_id=\"$job_id\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n  ) by (mountpoint)\n) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Network Traffic (Aggregate)",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_network_receive_bytes_total{job=\"node_exporter\"}[$__rate_interval]) * 8\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n)  by (device)",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "sum(\n  rate(node_network_transmit_bytes_total{job=\"node_exporter\"}[$__rate_interval]) * 8\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) by (device)",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "description": "Rate of packet-level errors for each network interface. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(node_network_receive_errs_total{job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) by (device)\n",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "sum(\n  rate(node_network_transmit_errs_total{job=\"node_exporter\"}[$__rate_interval])\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) by (device)\n",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "EFA Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(\n  rate(node_amazonefa_tx_bytes_total{job=\"efa_exporter\"}[$__rate_interval]) * 8\n  * on(slurm_node) group_left(job_id, job_name)\n  label_replace(slurm_job_node_info{job_id=\"$job_id\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n) by (slurm_node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}