{
 "title": "Partition Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "query": {
     "query": "label_values(slurm_job_node_info,partition)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Partitions Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Allocated to Partition",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(slurm_job_node_info{partition=\"$partition\"}) or on () vector (0)",
     "legendFormat": "Node Count"
    }
   ]
  },
  {
   "title": "Partition Nodes Currently Allocated to Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "group by (instance, instance_id, instance_type, slurm_node) (\n  node_uname_info{job=\"node_exporter\"}\n    * on(slurm_node) group_left()\n    group by (slurm_node) (\n      label_replace(slurm_job_node_info{partition=\"$partition\", job=\"slurm_exporter\"}, \"slurm_node\", \"$1\", \"node_name\", \"(.*)\")\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Jobs per Partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (slurm_partition_jobs_pending{partition=\"$partition\"} or (absent(slurm_partition_jobs_pending{partition=\"$partition\"}) * 0))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Partition Job History",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "group by (job_id, job_name) (\nslurm_job_node_info{partition=\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}