# Target rules
all: build
	@echo "Building pcluster_2az_fsxl_scratch"

build: assets

assets:
	@echo "Build assets for pcluster_2az_fsxl_scratch"

run: build
	@echo "Run assets for pcluster_2az_fsxl_scratch"

test: build

clean:

clobber: clean