AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an FSxL filesystem of PERSISENT_2 type plus the Security Group needed for use with ParallelCluster

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Filesystem Options
        Parameters:
          - Capacity
          - PerUnitStorageThroughput
          - Compression
          - LustreVersion
      - Label:
          default: Networking and Access
        Parameters:
          - VpcId
          - SubnetId

Parameters:
  VpcId:
    Description: VPC where you will deploy the FSx filesystem
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Description: Subnet where you will deploy the FSx filesystem (must be in same VPC)
    Type: AWS::EC2::Subnet::Id
  Capacity:
    Description: Storage capacity in GiB (1200 or increments of 2400)
    Type: Number
    Default: 1200
  PerUnitStorageThroughput:
    Description: Provisioned Read/Write (MB/s/TiB)
    Type: Number
    Default: 1000
    AllowedValues:
      - 125
      - 250
      - 500
      - 1000
  Compression:
    Description: Data compression type
    Type: String
    AllowedValues:
      - "LZ4"
      - "NONE"
    Default: "LZ4"
  LustreVersion:
    Description: Lustre software version
    Type: String
    AllowedValues:
      - "2.15"
      - "2.12"
    Default: "2.12"

Resources:

  LustreServersSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: 'Allows traffic to FSx for Lustre filesystem'
        GroupName: !Sub '${AWS::StackName}-fsxl-security-group'
        VpcId: !Ref VpcId

  LustreClientsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Clients join this group for access to FSx for Lustre filesystem'
      GroupName: !Sub '${AWS::StackName}-fsxl-client-security-group'
      VpcId: !Ref VpcId

  LustreClientsSGfromLustreClients988:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on port 988 between Lustre clients
      FromPort: 988
      ToPort: 988
      GroupId: !Ref LustreClientsSG
      SourceSecurityGroupId: !Ref LustreClientsSG

  LustreClientsSGxxFROMxxLustreServersSG988:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on port 988 between Amazon FSx for Lustre file servers and Lustre clients
      FromPort: 988
      ToPort: 988
      GroupId: !Ref LustreClientsSG
      SourceSecurityGroupId: !Ref LustreServersSG

  LustreClientsSGfromLustreClients1021:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on ports 1021-23 between Amazon FSx for Lustre file servers
      FromPort: 1021
      ToPort: 1023
      GroupId: !Ref LustreClientsSG
      SourceSecurityGroupId: !Ref LustreClientsSG
  
  LustreClientsSGxxFROMxxLustreServersSG1021:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on ports 1021-23 between Amazon FSx for Lustre file servers and Lustre clients
      FromPort: 1021
      ToPort: 1023
      GroupId: !Ref LustreClientsSG
      SourceSecurityGroupId: !Ref LustreServersSG
  
  LustreClientsSGtoLustreClients988:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      Description: Allow Lustre traffic on por 988 between Amazon FSx for Lustre clients
      FromPort: 988
      ToPort: 988
      GroupId: !Ref LustreClientsSG
      DestinationSecurityGroupId: !Ref LustreClientsSG
  
  LustreClientsSGtopclusterLustreServersSG:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      Description: Allow Lustre traffic on port 988 between Amazon FSx for Lustre file servers and Lustre clients
      FromPort: 988
      ToPort: 988
      GroupId: !Ref LustreClientsSG
      DestinationSecurityGroupId: !Ref LustreServersSG

  LustreClientsSGtoLustreClients1021:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on ports 1021-23 between Amazon FSx for Lustre clients
      FromPort: 1021
      ToPort: 1023
      GroupId: !Ref LustreClientsSG
      DestinationSecurityGroupId: !Ref LustreClientsSG

  LustreClientsSGtoLustreServersSG:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      Description: Allows Lustre traffic on ports 1021-23 between Amazon FSx for Lustre file servers and Lustre clients
      FromPort: 1021
      ToPort: 1023
      GroupId: !Ref LustreClientsSG
      DestinationSecurityGroupId: !Ref LustreServersSG

  FSxLFilesystem:
    Type: AWS::FSx::FileSystem
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      FileSystemType: LUSTRE
      StorageType: SSD
      FileSystemTypeVersion: !Ref LustreVersion
      StorageCapacity: !Ref Capacity
      SecurityGroupIds:
        - !Ref LustreServersSG
        - !Ref LustreClientsSG
      SubnetIds:
        - !Ref SubnetId
      LustreConfiguration:
        DataCompressionType: !Ref Compression
        DeploymentType: PERSISTENT_2
        PerUnitStorageThroughput: !Ref PerUnitStorageThroughput

Outputs:
  FSxLustreFilesystemId:
    Description: The ID of the FSxL filesystem that has been created
    Value: !Ref FSxLFilesystem
    Export:
      Name: !Sub ${AWS::StackName}-FSxLustreFilesystemId
  FSxLustreSecurityGroupId:
    Description: The ID of the security group allowing access to FSxL filesystem
    Value: !Ref LustreClientsSG
    Export:
      Name: !Sub ${AWS::StackName}-FSxLustreSecurityGroupId
