AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS ParallelCluster CloudFormation Template

Parameters:
  HeadNodeSubnet:
    Description: Subnet where the HeadNode will run
    Type: AWS::EC2::Subnet::Id

  ComputeSubnet:
    Description: Subnet where the Compute Nodes will run
    Type: AWS::EC2::Subnet::Id

  KeyName:
    Description: KeyPair to login to the head node
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  PclusterCfn:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParallelClusterVersion: 3.6.0
      TemplateURL: !Sub
        - https://${Region}-aws-parallelcluster.s3.${Region}.amazonaws.com/parallelcluster/${Version}/templates/parallelcluster/cluster.yaml
        - { Version: 3.5.0, Region: !Ref AWS::Region }
      TimeoutInMinutes: 10

  PclusterCluster:
    Type: Custom::PclusterCluster
    Properties:
      ServiceToken: !GetAtt [ PclusterCfn , Outputs.Function ]
      ClusterName: !Sub 'c-${AWS::StackName}'
      ClusterConfiguration:
        Image:
          Os: alinux2
        HeadNode:
          InstanceType: t2.medium
          Networking:
            SubnetId: !Ref HeadNodeSubnet
          Ssh:
            KeyName: !Ref KeyName
        Scheduling:
          Scheduler: slurm
          SlurmQueues:
          - Name: queue0
            ComputeResources:
            - Name: queue0-i0
              InstanceType: t2.micro
              MinCount: 0
              MaxCount: 10
            Networking:
              SubnetIds:
              - !Ref ComputeSubnet