AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS ParallelCluster CloudFormation Template

Parameters:
  ParallelClusterVersion:
    Description: The version of AWS ParallelCluster to use
    Type: String
    Default: 3.5.0

  SourceBucket:
    Description: Bucket to pull templates from
    Type: String
    Default: aws-parallelcluster-dev-cgruenwa

  ClusterName:
    Description: Name of cluster. Note this must be different than the stack name.
    Type: String
    Default: mycluster

  AvailabilityZone:
    Description: Availability zone where instances will be launched
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-2a

  ComputeInstanceMax:
    Description: Maximum number of compute instances
    Type: Number
    Default: 10

  KeyName:
    Description: KeyPair to login to the head node
    Type: AWS::EC2::KeyPair::KeyName

  OS:
    Type: String
    Default: alinux2
    AllowedValues:
      - alinux2
      - centos7
      - ubuntu1804
      - ubuntu2004
    Description: Enter alinux2, centos7, ubuntu1804 or ubuntu2004. Default is alinux2.

  AccoutingDatabaseAdmin

Resources:

  PclusterCfn:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParallelClusterVersion: !Ref ParallelClusterVersion
        SourceBucket: !Ref SourceBucket
      TemplateURL: !Sub
        - https://${Bucket}.s3.${Region}.amazonaws.com/pcluster-cfn.yaml
        - { Bucket: !Ref SourceBucket, Region: !Ref AWS::Region }
      TimeoutInMinutes: 10

  PclusterVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        InternetGatewayId: ''
        PublicCIDR: 10.0.0.0/24
        PrivateCIDR: 10.0.16.0/20
        AvailabilityZone: !Ref AvailabilityZone
      TemplateURL: !Sub
        - https://${Bucket}.s3.${Region}.amazonaws.com/networking.yaml
        - { Bucket: !Ref SourceBucket, Region: !Ref AWS::Region }
      TimeoutInMinutes: 10

  PclusterCluster:
    Type: Custom::PclusterCluster
    Properties:
      ServiceToken: !GetAtt [ PclusterCfn , Outputs.Function ]
      ClusterName: !Ref ClusterName
      ClusterConfiguration:
        Image:
          Os: !Ref OS
        HeadNode:
          InstanceType: t2.large
          Networking:
            SubnetId: !GetAtt [ PclusterVpc , Outputs.PublicSubnetId ]
          Ssh:
            KeyName: !Ref KeyName
        Scheduling:
          Scheduler: slurm
          SlurmQueues:
          - Name: queue0
            ComputeResources:
            - Name: queue0-i0
              InstanceType: t2.micro
              MinCount: 0
              MaxCount: !Ref ComputeInstanceMax
            Networking:
              SubnetIds:
              - !GetAtt [ PclusterVpc , Outputs.PublicSubnetId ]

  PclusterSlurmAcctDb:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClusterName: pcluster-slurm-db
        ClusterAdmin: admin
        AdminPasswordSecretString: qSKc&292hYX!
        MinCapacity: 1
        MaxCapacity: 2
        Vpc: 


