# Target rules
all: build
	@echo "Building dlami_for_pcs"

build: assets

assets:
	@echo "Build assets for dlami_for_pcs"

run: build
	@echo "Run assets for dlami_for_pcs"

test: build

clean:

clobber: clean
