# Target rules
all: build
	@echo "Building hpc_zonal_networking"

build: assets

assets:
	@echo "Build assets for hpc_zonal_networking"

run: build
	@echo "Run assets for hpc_zonal_networking"

test: build

clean:

clobber: clean