# Target rules
all: build
	@echo "Building slurm_accounting"

build: assets

assets:
	@echo "Build assets for slurm_accounting"

run: build
	@echo "Run assets for slurm_accounting"

test: build

clean:

clobber: clean