# Target rules
all: build
	@echo "Building slurm_accounting_with_email"

build: assets

assets:
	@echo "Build assets for slurm_accounting_with_email"

run: build
	@echo "Run assets for slurm_accounting_with_email"

test: build

clean:

clobber: clean