# Target rules
all: build
	@echo "Building mountpoint_s3"

build: assets

assets:
	@echo "Build assets for mountpoint_s3"

run: build
	@echo "Run assets for mountpoint_s3"

test: build

clean:

clobber: clean