# Target rules
all: build
	@echo "Building rest_api_cognito"

build: assets

assets:
	@echo "Build assets for rest_api_cognito"

run: build
	@echo "Run assets for rest_api_cognito"

test: build

clean:

clobber: clean
