AWSTemplateFormatVersion: 2010-09-09
Description: Create a security group to enables EFA traffic

Parameters:
  SecurityGroupName:
    Description: Name of your EFA security group
    Type: String
    Default: efa-sg
  VPC:
    Description: VPC where the Elastic Fabric Adapters will be created
    Type: 'AWS::EC2::VPC::Id'

Resources:

  EfaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Support EFA
      GroupName: !Ref SecurityGroupName
      VpcId: !Ref VPC

  EfaSecurityGroupOutboundSelfRule:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      IpProtocol: '-1'
      GroupId: !Ref EfaSecurityGroup
      Description: Allow outbound EFA traffic to SG members
      DestinationSecurityGroupId: !Ref EfaSecurityGroup

  EfaSecurityGroupInboundSelfRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: '-1'
      GroupId: !Ref EfaSecurityGroup
      Description: Allow inbound EFA traffic to SG members
      SourceSecurityGroupId: !Ref EfaSecurityGroup

Outputs:
  EfaSecurityGroupId:
    Description: A security group that enables EFA traffic
    Value: !Ref EfaSecurityGroup
