# Target rules
all: build
	@echo "Building fsxl_secgroup"

build: assets

assets:
	@echo "Build assets for fsxl_secgroup"

run: build
	@echo "Run assets for fsxl_secgroup"

test: build

clean:

clobber: clean