# Target rules
all: build
	@echo "Building demo_managed_ad"

build: assets

assets:
	@echo "Build assets for demo_managed_ad"

run: build
	@echo "Run assets for demo_managed_ad"

test: build

clean:

clobber: clean