# Target rules
all: build
	@echo "Building cloudwatch"

build: assets

assets:
	@echo "Build assets for cloudwatch"

run: build
	@echo "Run assets for cloudwatch"

test: build

clean:

clobber: clean
