# Target rules
all: build
	@echo "Building parallelcluster_ui"

build: assets

assets:
	@echo "Build assets for parallelcluster_ui"

run: build
	@echo "Run assets for parallelcluster_ui"

test: build

clean:

clobber: clean