import pathlib
import sys
import unittest


sys.path.insert(0, str(pathlib.Path(__file__).parents[1] / "assets" / "lambda"))

import accounting_fields
import sacctmgr_load
from configuration import normalize_configuration
from sacctmgr_load import parse_sacctmgr_load


SAMPLE_DUMP = """\
# Generated by sacctmgr dump
QOS - 'normal':Description='Normal: work':Priority=100:GrpJobs=10:GrpTRES=cpu=32,mem=1G
Cluster - 'source-cluster':FairShare=1
Parent - 'root'
Account - 'research':Description='Research':Organization='Example':FairShare=10:DefaultQOS='normal':QOS='normal'
Parent - 'research'
User - 'alice':DefaultAccount='research':DefaultWCKey='primary':WCKeys='primary,secondary':AdminLevel='Operator':Coordinator='research':FairShare=5:DefaultQOS='normal':QOS='normal'
"""

PCS_25_11_DUMP = (
    pathlib.Path(__file__).parent
    / "fixtures"
    / "pcs-25.11-sacctmgr.dump"
).read_text()


class SacctmgrLoadTests(unittest.TestCase):
    def test_field_mappings_cover_the_structured_schema(self):
        qos_destinations = {
            path
            for path, _ in sacctmgr_load.QOS_FIELDS.values()
        }
        self.assertEqual(qos_destinations, accounting_fields.QOS_FIELDS)

        association_context_fields = {
            "account",
            "cluster",
            "is_default",
            "parent_account",
            "partition",
            "user",
        }
        association_destinations = {
            path
            for path, _ in sacctmgr_load.ASSOCIATION_FIELDS.values()
        }
        self.assertEqual(
            association_destinations | association_context_fields,
            accounting_fields.ASSOCIATION_FIELDS,
        )

    def test_parses_every_qos_action_field(self):
        values = {
            "csv": "secondary",
            "float_limit": "1.5",
            "limit": "1",
            "minutes": "10",
            "preempt_modes": "cancel",
            "qos_flags": "NoDecay",
            "seconds": "30",
            "string": "value",
            "tres": "cpu=1",
            "uint": "1",
        }
        for option, (path, value_type) in sacctmgr_load.QOS_FIELDS.items():
            with self.subTest(option=option):
                parsed = parse_sacctmgr_load(
                    f"QOS - 'normal':{option}='{values[value_type]}'\n"
                    "Cluster - 'source'\n"
                )
                value = parsed["qos"]["normal"]
                for key in path.split("."):
                    value = value[key]

    def test_parses_every_association_action_field(self):
        values = {
            "csv": "normal",
            "limit": "1",
            "minutes": "10",
            "shares": "1",
            "string": "normal",
            "tres": "cpu=1",
        }
        for option, (path, value_type) in (
            sacctmgr_load.ASSOCIATION_FIELDS.items()
        ):
            with self.subTest(option=option):
                parsed = parse_sacctmgr_load(
                    "QOS - 'normal'\n"
                    "Cluster - 'source'\n"
                    "Parent - 'root'\n"
                    f"Account - 'research':{option}="
                    f"'{values[value_type]}'\n"
                )
                value = parsed["associations"][0]
                for key in path.split("."):
                    value = value[key]

    def test_parses_canonical_dump_records(self):
        parsed = parse_sacctmgr_load(SAMPLE_DUMP)

        self.assertEqual(
            parsed["qos"]["normal"]["description"],
            "Normal: work",
        )
        self.assertEqual(
            parsed["qos"]["normal"]["limits"]["max"]["tres"]["total"],
            [
                {"type": "cpu", "count": 32},
                {"type": "mem", "count": 1024},
            ],
        )
        self.assertEqual(
            parsed["users"]["alice"]["coordinators"],
            ["research"],
        )

    def test_parses_26_05_typed_tres_names(self):
        parsed = parse_sacctmgr_load(
            "QOS - 'gpu':GrpTRES=gres/gpu:a100=4,gres/gpu:h100=8"
            ":MaxJobsPU=2\n"
            "Cluster - 'source'\n"
        )

        self.assertEqual(
            parsed["qos"]["gpu"]["limits"]["max"]["tres"]["total"],
            [
                {"type": "gres", "name": "gpu:a100", "count": 4},
                {"type": "gres", "name": "gpu:h100", "count": 8},
            ],
        )
        self.assertEqual(
            parsed["qos"]["gpu"]["limits"]["max"]["jobs"]["active_jobs"][
                "per"
            ]["user"],
            2,
        )

    def test_parses_literal_pcs_25_11_dump_output(self):
        parsed = normalize_configuration(
            {"sacctmgr_load": PCS_25_11_DUMP},
            "pcs-slurm-bootstrap-it",
        )

        self.assertEqual(
            [account["name"] for account in parsed["accounts"]],
            ["engineering", "simulation"],
        )
        self.assertEqual(
            [qos["name"] for qos in parsed["qos"]],
            ["normal", "preempt"],
        )
        self.assertEqual(
            [user["name"] for user in parsed["users"]],
            ["root", "tfuser"],
        )
        self.assertEqual(
            [
                (
                    association["account"],
                    association["user"],
                    association.get("parent_account"),
                )
                for association in parsed["associations"]
            ],
            [
                ("root", None, None),
                ("engineering", None, "root"),
                ("simulation", None, "engineering"),
                ("root", "root", None),
                ("engineering", "tfuser", None),
            ],
        )

    def test_normalizes_dump_for_target_cluster(self):
        normalized = normalize_configuration(
            {"sacctmgr_load": SAMPLE_DUMP},
            "target-cluster",
        )

        self.assertEqual(
            [association["account"] for association in normalized["associations"]],
            ["root", "research", "research"],
        )
        self.assertTrue(normalized["associations"][-1]["is_default"])
        self.assertTrue(
            all(
                association["cluster"] == "target-cluster"
                for association in normalized["associations"]
            )
        )
        self.assertEqual(
            {wckey["name"] for wckey in normalized["wckeys"]},
            {"primary", "secondary"},
        )
        self.assertEqual(
            normalized["coordinators"][0]["users"],
            ["alice"],
        )

    def test_rejects_unsupported_dump_option_with_line_number(self):
        with self.assertRaisesRegex(
            ValueError,
            "line 2: comment: unsupported option",
        ):
            parse_sacctmgr_load(
                "Cluster - 'source'\n"
                "User - 'alice':Comment='not portable'\n"
            )

    def test_rejects_qos_after_cluster(self):
        with self.assertRaisesRegex(
            ValueError,
            "QOS records must precede",
        ):
            parse_sacctmgr_load(
                "Cluster - 'source'\n"
                "QOS - 'normal'\n"
            )
