# Target rules
all: build
	@echo "Building nist_800_223"

build: assets

assets:
	@echo "Build assets for nist_800_223"

run: build
	@echo "Run assets for nist_800_223"

test: build

clean:

clobber: clean