# Target rules
all: build
	@echo "Building try_graviton"

build: assets

assets:
	@echo "Build assets for try_graviton"

run: build
	@echo "Run assets for try_graviton"

test: build

clean:

clobber: clean