# Target rules
all: build
	@echo "Building res_demo_env"

build: assets

assets:
	@echo "Build assets for res_demo_env"

run: build
	@echo "Run assets for res_demo_env"

test: build

clean:

clobber: clean