# Target rules
all: build
	@echo "Building fsx_lustre_scheduled_drt_release"

build: assets

assets:
	@echo "Build assets for fsx_lustre_scheduled_drt_release"

run: build
	@echo "Run assets for fsx_lustre_scheduled_drt_release"

test: build

clean:

clobber: clean