# Target rules
all: build
	@echo "Building slurm_accounting_db_amazon_aurora"

build: assets

assets:
	@echo "Build assets for slurm_accounting_db_amazon_aurora"

run: build
	@echo "Run assets for slurm_accounting_db_amazon_aurora"

test: build

clean:

clobber: clean