# Target rules
all: build
	@echo "Building shared_home"

build: assets

assets:
	@echo "Build assets for shared_home"

run: build
	@echo "Run assets for shared_home"

test: build

clean:

clobber: clean