# Target rules
all: build
	@echo "Building byo_login_node"

build: assets

assets:
	@echo "Build assets for byo_login_node"

run: build
	@echo "Run assets for byo_login_node"

test: build

clean:

clobber: clean