# Target rules
all: build
	@echo "Building demo_openldap"

build: assets

assets:
	@echo "Build assets for demo_openldap"

run: build
	@echo "Run assets for demo_openldap"

test: build

clean:

clobber: clean