# Target rules
all: build
	@echo "Building autoupdate_cngs"

build: assets

assets:
	@echo "Build assets for autoupdate_cngs"

run: build
	@echo "Run assets for autoupdate_cngs"

test: build

clean:

clobber: clean