# Target rules
all: build
	@echo "Building res_blue_green"

build: assets

assets:
	@echo "Build assets for res_blue_green"

run: build
	@echo "Run assets for res_blue_green"

test: build

clean:

clobber: clean
