# Target rules
all: build
	@echo "Building fsx_openzfs"

build: assets

assets:
	@echo "Build assets for fsx_openzfs"

run: build
	@echo "Run assets for fsx_openzfs"

test: build

clean:

clobber: clean