# Target rules
all: build
	@echo "Building hpc_networking_2az"

build: assets

assets:
	@echo "Build assets for hpc_networking_2az"

run: build
	@echo "Run assets for hpc_networking_2az"

test: build

clean:

clobber: clean