AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Parallel Computing Service Cluster creation

Parameters:

  KeyName:
    Description: KeyPair to login to the head node
    Type: AWS::EC2::KeyPair::KeyName
    AllowedPattern: ".+"  # Required

  AmiId:
    Description: (Optional) ID of the AMI that the compute / login node groups run. Defaults to sample ami.
    Type: String
    Default: ''

  ClientIpCidr:
    Description: Default IP(s) allowed to directly access the login nodes.
    Default: 127.0.0.1/32
    Type: String
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Value must be a valid IP or network range of the form x.x.x.x/x.

Resources:

  PCSCfnProvider:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://aws-hpc-recipes.s3.amazonaws.com/main/recipes/pcs/getting_started/assets/pcs-cfn.yaml

  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProvisionSubnetsC: "False"
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/net/hpc_large_scale/assets/main.yaml

  EfsStorage:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SubnetIds: !GetAtt [ Networking, Outputs.DefaultPrivateSubnet ]
        SubnetCount: 1
        VpcId: !GetAtt [ Networking, Outputs.VPC ]
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/efs_simple/assets/main.yaml

  FSxLStorage:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PerUnitStorageThroughput: 125
        SubnetId: !GetAtt [ Networking, Outputs.DefaultPrivateSubnet ]
        VpcId: !GetAtt [ Networking, Outputs.VPC ]
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/fsx_lustre/assets/persistent.yaml

  PCSSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClientIpCidr: !Ref ClientIpCidr
        VpcId: !GetAtt [ Networking, Outputs.VPC ]
      TemplateURL: https://aws-hpc-recipes.s3.amazonaws.com/main/recipes/pcs/getting_started/assets/pcs-cluster-sg.yaml

  # Cluster

  PCSCluster:
    Type: Custom::Resource
    Properties:
      ServiceToken: !GetAtt [ PCSCfnProvider, Outputs.ServiceToken ]
      clusterName: !Sub '${AWS::StackName}'
      size: SMALL
      scheduler:
        type: SLURM
        version: 23.11
      networking:
        subnetIds:
          - !GetAtt [ Networking, Outputs.DefaultPrivateSubnet ]
        securityGroupIds:
          - !GetAtt [ PCSSecurityGroup, Outputs.ClusterSecurityGroupId ]

  # Compute Node groups
  PCSInstanceProfile:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RoleName: !Sub 'instance-role-${AWS::StackName}'
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/pcs/getting_started/assets/pcs-iip-minimal.yaml

  PCSLaunchTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcDefaultSecurityGroupId: !GetAtt [ Networking, Outputs.SecurityGroup ]
        ClusterSecurityGroupId: !GetAtt [ PCSSecurityGroup, Outputs.ClusterSecurityGroupId ]
        SshSecurityGroupId: !GetAtt [ PCSSecurityGroup, Outputs.InboundSshSecurityGroupId ]
        SshKeyName: !Ref KeyName
        EfsFilesystemId: !GetAtt [ EfsStorage, Outputs.EFSFilesystemId ]
        FSxLustreFilesystemId: !GetAtt [ FSxLStorage, Outputs.FSxLustreFilesystemId ]
        FSxLustreFilesystemMountName: !Sub 'pcs-mount-${AWS::StackName}'
      TemplateURL: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/pcs/getting_started/assets/pcs-lt-efs-fsxl.yaml

  # Compute Node groups - Login Nodes
  PCSNodeGroupLogin:
    Type: Custom::Resource
    Properties:
      ServiceToken: !GetAtt [ PCSCfnProvider, Outputs.ServiceToken ]
      clusterIdentifier: !GetAtt [ PCSCluster, id ]
      computeNodeGroupName: login
      scalingConfiguration:
        minInstanceCount: 1
        maxInstanceCount: 1
      iamInstanceProfileArn: !GetAtt [ PCSInstanceProfile, Outputs.InstanceProfileArn ]
      customLaunchTemplate:
        id: !GetAtt [ PCSLaunchTemplate, Outputs.LoginLaunchTemplateId ]
        version: 1
      subnetIds:
        - !GetAtt [ Networking, Outputs.DefaultPublicSubnet ]
      amiId: !Ref AmiId
      instanceConfigs:
        - instanceType: c6i.xlarge

  PCSQueueLogin:
    Type: Custom::Resource
    Properties:
      ServiceToken: !GetAtt [ PCSCfnProvider, Outputs.ServiceToken ]
      clusterIdentifier: !GetAtt [ PCSCluster, id ]
      queueName: login
      computeNodeGroupConfigurations:
        - computeNodeGroupId: !GetAtt [ PCSNodeGroupLogin, id ]

  # Compute Node groups - Compute Nodes
  PCSNodeGroupCompute:
    Type: Custom::Resource
    Properties:
      ServiceToken: !GetAtt [ PCSCfnProvider, Outputs.ServiceToken ]
      clusterIdentifier: !GetAtt [ PCSCluster, id ]
      computeNodeGroupName: compute
      scalingConfiguration:
        minInstanceCount: 0
        maxInstanceCount: 4
      iamInstanceProfileArn: !GetAtt [ PCSInstanceProfile, Outputs.InstanceProfileArn ]
      customLaunchTemplate:
        id: !GetAtt [ PCSLaunchTemplate, Outputs.ComputeLaunchTemplateId ]
        version: 1
      subnetIds:
        - !GetAtt [ Networking, Outputs.DefaultPrivateSubnet ]
      amiId: !Ref AmiId
      instanceConfigs:
        - instanceType: c6i.xlarge

  PCSQueueCompute:
    Type: Custom::Resource
    Properties:
      ServiceToken: !GetAtt [ PCSCfnProvider, Outputs.ServiceToken ]
      clusterIdentifier: !GetAtt [ PCSCluster, id ]
      queueName: compute
      computeNodeGroupConfigurations:
        - computeNodeGroupId: !GetAtt [ PCSNodeGroupCompute, id ]

Outputs:
  ClusterId:
    Description: The ID of the PCS cluster
    Value: !GetAtt [ PCSCluster, id ]
