# Target rules
all: build
	@echo "Building res_ready_imagebuilder_components"

build: assets

assets:
	@echo "Build assets for res_ready_imagebuilder_components"

run: build
	@echo "Run assets for res_ready_imagebuilder_components"

test: build

clean:

clobber: clean