# Target rules
all: build
	@echo "Building login_nodes"

build: assets

assets:
	@echo "Build assets for login_nodes"

run: build
	@echo "Run assets for login_nodes"

test: build

clean:

clobber: clean