# Target rules
all: build
	@echo "Building cfd_cluster"

build: assets

assets:
	@echo "Build assets for cfd_cluster"

run: build
	@echo "Run assets for cfd_cluster"

test: build

clean:

clobber: clean