# Target rules
all: build
	@echo "Building multiuser_demo"

build: assets

assets:
	@echo "Build assets for multiuser_demo"

run: build
	@echo "Run assets for multiuser_demo"

test: build

clean:

clobber: clean