# Target rules
all: build
	@echo "Building hpc_recipes_101"

build: assets

assets:
	@echo "Build assets for hpc_recipes_101"

run: build
	@echo "Run assets for hpc_recipes_101"

test: build

clean:

clobber: clean