# Target rules
all: build
	@echo "Building fsx_lustre_s3_dra"

build: assets

assets:
	@echo "Build assets for fsx_lustre_s3_dra"

run: build
	@echo "Run assets for fsx_lustre_s3_dra"

test: build

clean:

clobber: clean