# Target rules
all: build
	@echo "Building public_certs"

build: assets

assets:
	@echo "Build assets for public_certs"

run: build
	@echo "Run assets for public_certs"

test: build

clean:

clobber: clean
