# Target rules
all: build
	@echo "Building observability_for_pcs"

build: assets

assets:
	@echo "Build assets for observability_for_pcs"

run: build
	@echo "Run assets for observability_for_pcs"

test: build

clean:

clobber: clean