# Target rules
all: build
	@echo "Building getting_started"

build: assets

assets:
	@echo "Build assets for getting_started"

run: build
	@echo "Run assets for getting_started"

test: build

clean:

clobber: clean