AWSTemplateFormatVersion: '2010-09-09'
Description: ImageBuilder Components for RES-ready AMIs

### Stack metadata
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: HPC Recipes Configuration
        Parameters:
          - HpcRecipesS3Bucket
          - HpcRecipesBranch

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: HPC Recipes for AWS S3 bucket
    AllowedValues:
         - aws-hpc-recipes
         - aws-hpc-recipes-dev
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: HPC Recipes for AWS release branch
    AllowedPattern: '^(?!.*/\.git$)(?!.*/\.)(?!.*\\.\.)[a-zA-Z0-9-_\.]+$'

Resources:

  RESVDILinuxStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/res/res_ready_ami/assets/components/research-and-engineering-studio-vdi-linux.yaml'
      TimeoutInMinutes: 10

  RESVDIWindowsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/res/res_ready_ami/assets/components/research-and-engineering-studio-vdi-windows.yaml'
      TimeoutInMinutes: 10


Outputs:
  RESVDILinuxComponent:
    Description: RESVDILinuxComponent
    Value: !GetAtt [ RESVDILinuxStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-RESVDILinuxComponent"
  RESVDIWindowsComponent:
    Description: RESVDIWindowsComponent
    Value: !GetAtt [ RESVDIWindowsStack, Outputs.ImageBuilderComponent ]
    Export:
      Name: !Sub "${AWS::StackName}-RESVDIWindowsComponent"
