# Target rules
all: build
	@echo "Building hpc_large_scale"

build: assets

assets:
	@echo "Build assets for hpc_large_scale"

run: build
	@echo "Run assets for hpc_large_scale"

test: build

clean:

clobber: clean