# Target rules
all: build
	@echo "Building efs_decoupled_storage"

build: assets

assets:
	@echo "Build assets for efs_decoupled_storage"

run: build
	@echo "Run assets for efs_decoupled_storage"

test: build

clean:

clobber: clean